apiVersion: v1
kind: Service
metadata:
  name: android-emulator
  labels:
    name: android-emulator
spec:
  selector:
    app: android-emulator
  type: LoadBalancer  
  ports:
    - name: web
      protocol: TCP
      port: 4723
      targetPort: 4723
      nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: android-emulator-deploy
  labels:
    app: android-emulator-deploy
    name: android-emulator-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emulator-test
  template:
    metadata:
      labels:
        app: emulator-test
    spec:
      containers:
        - name: android-emulator-container
          image: venmaum/udaystj:latest
          env:
            - name: SELENIUM_HOST
              value: "selenium-hub"
            - name: SELENIUM_PORT
              value: "4444"
            - name: EMULATOR_HOSTNAME
              value: "android-emulator"     
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-ec","tail -f /dev/null &",
                "/opt/android-sdk/ma/android-emulator/run_emulators.sh","/opt/android-sdk/ma/android-emulator/connect_emulators_tosgrid.sh 'Nexus-1,Nexus-2' $SELENIUM_HOST $SELENIUM_PORT $EMULATOR_HOSTNAME"]
          resources:
            limits:
              memory: "8Gi"
              cpu: "2"
            requests:
              memory: "4Gi"
              cpu: "1"
          ports:
            - containerPort: 4723
              protocol: TCP          
