apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2020-07-20T01:17:09Z"
  labels:
    controller-uid: bbb73552-ca26-11ea-ba5a-08002798c22e
    job-name: busybox
  name: busybox
  namespace: default
  resourceVersion: "20460"
  selfLink: /apis/batch/v1/namespaces/default/jobs/busybox
  uid: bbb73552-ca26-11ea-ba5a-08002798c22e
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: bbb73552-ca26-11ea-ba5a-08002798c22e
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: bbb73552-ca26-11ea-ba5a-08002798c22e
        job-name: busybox
    spec:
      containers:
      - command:
        - echo
        - Hello I am from job
        image: busybox
        imagePullPolicy: Always
        name: busybox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
