apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2020-07-20T01:17:09Z"
  labels:
    job-name: busybox
  name: busybox
  namespace: default
spec:
  backoffLimit: 6
  completions: 10
  parallelism: 10
  template:
    metadata:
      labels:
        job-name: busybox
    spec:
      containers:
      - command:
        - echo
        - Hello I am from job
        image: busybox
        imagePullPolicy: Always
        name: busybox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
